# Generated by Django 2.0.3 on 2018-03-20 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsite', '0002_auto_20180311_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
