# Generated by Django 2.0.1 on 2018-03-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsite', '0005_auto_20180327_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='petName',
            new_name='pet_name',
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.CharField(default='\n        http://papapodari.com.ua\n        /sites/default/files\n        /node/product/vinny_pux_4.jpg\n        ', max_length=200),
        ),
        migrations.AlterField(
            model_name='pet',
            name='last_seen_place',
            field=models.CharField(default='Somewhere above the sky', max_length=100),
        ),
    ]
