# Generated by Django 2.0.1 on 2018-03-28 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petsite', '0006_auto_20180328_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='author',
            field=models.ForeignKey(default='mister null', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.CharField(default='http://papapodari.com.ua/sites/default/files/node/product/vinny_pux_4.jpg', max_length=200),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
