# Generated by Django 2.0.1 on 2018-03-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsite', '0007_auto_20180328_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='fame',
            field=models.IntegerField(default=0),
        ),
    ]
