# Generated by Django 2.0.1 on 2018-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsite', '0012_pet_postedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
